### ISSUE TITLE
BUG: PSSE throw the Exception while Dynamic simulation

### ISSUE THREAD

**Issue by yim0331** [tdcosim/TDcoSim#14] opened 2019-11-20 21:43 UTC
**Describe the bug**
There is an unexpected exception from PSSE while running a dynamic simulation with the attached config.json

The exceptional point is:
self._tnet_model.runDynamic(t) in default_dynamic_procedure.py

The config.json is:

{
    "cosimHome": ".\\tdcosim",
    "psseConfig":{
        "rawFilePath":".\\SampleData\\TNetworks\\118bus\\case118.raw",
        "dyrFilePath":".\\SampleData\\TNetworks\\118bus\\case118.dyr"        
    },
    "openDSSConfig":{        
        "defaultFeederConfig":{
            "filePath":[".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
            "solarFlag":0,
            "solarPenetration":0.0
        },
		"manualFeederConfig":{
            "nodes": [
                {
                    "nodenumber": 1,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 2,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 3,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 4,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 7,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 8,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 11,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 12,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 13,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 14,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 15,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 16,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 17,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 18,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 19,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 20,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 21,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 22,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 27,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 28,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 29,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 31,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 32,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 33,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 34,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 35,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 36,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 39,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 43,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 113,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 114,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 115,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                },
				{
                    "nodenumber": 117,
                    "filePath": [".\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":0,
                    "solarPenetration":0.0,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                }                            
            ]
        }
    },
    "simulationConfig":{
        "simType":"dynamic",
        "dynamicConfig":{
            "events":{
                "1":{
                     "time":2.0,
                    "type":"faultOn",
                    "faultBus":17,
                    "faultImpedance":[0.0,-1E11]
                },
                "2":{
                    "type":"faultOff",
                    "time":2.1,
                    "faultBus":17
                },
                "3":{
                    "type":"simEnd",
                    "time":15.0
                }
            }
        },
        "staticConfig":{
            "loadShape": [0.81518164, 0.77456979, 0.74237094, 0.72439771, 0.71946463,
            0.72891013, 0.75212237, 0.76833652, 0.783174  , 0.79468451,
            0.80634799, 0.80370937, 0.8016826 , 0.79288719, 0.79437859,
             0.79720841, 0.82271511, 0.92470363, 1.0, 0.99021033,
             0.97101338, 0.94042065, 0.88397706, 0.81097514]
        },
        "protocol":"loose_coupling"
    },
    "outputConfig":{
        "outputfilename": "output.csv",
        "type": "csv"
    }
}

**Comment by sibyjackgrove** [comment] 2020-03-04 18:47
The exception is due to a memory error. It is caused because psspy is unable to access more than 2 GB of memory since it uses 32 bit Python 2.7.
Duplicate of #13

**Closed by sibyjackgrove** 2020-03-04 18:47 UTC
Labels: bug
