### ISSUE TITLE
BUG: Trying to get into "pvder_aggregate.py"

### ISSUE THREAD

**Issue by electrosam029** [tdcosim/TDcoSim#17] opened 2019-12-13 15:03 UTC
**Describe the bug**
Warning: No handlers could be found for logger "SolarPV_DER_ThreePhase"

**To Reproduce**
Trying to run the given example files using time domain simulations.
Trying to get into "pvder_aggregate.py" class using breakpoints

**Expected behavior**
Simulation is configured for 10% PV penetration.
Simulation not pausing at "pvder_aggregate.py" breakpoints.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PSS/E Version :34

**Comment by sibyjackgrove** [comment] 2019-12-16 16:46
> Warning: No handlers could be found for logger "SolarPV_DER_ThreePhase"
This is not really a bug. It's just a warning output from the logger object that was created by the `SolarPV_DER_ThreePhase` instance. The logging level set to INFO to and it is supposed to print the details of the PV-DER object created. However, I am not sure why it prints this particular warning and need to look into it. But it doesn't impact the rest of the code in any way. 
So the bug
> Simulation not pausing at "pvder_aggregate.py" breakpoints.
must be caused by something else.

**Comment by sibyjackgrove** [comment] 2020-03-04 18:38
The warning will no longer be printed since I added a dummy logger. Resolved with 5531dee0183542d8a02251c2b8f1c0b304d9d994.

**Closed by sibyjackgrove** 2020-03-04 18:38 UTC
Labels: bug
